apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deploy
  labels:
    service: es-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      service: es-deploy
  template:
    metadata:
      labels:
        service: es-deploy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - es-deploy
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        image: elasticsearch:6.8.13
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 20
          periodSeconds: 30
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
          - mountPath: /data
            name: graylog-es
          - name: config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
      volumes:
        - name: graylog-es
          persistentVolumeClaim:
            claimName: graylog-es-pv
        - name: config
          configMap:
            name: es-config
---
apiVersion: v1
kind: Service
metadata:
  name: es6
spec:
  type: NodePort
  selector:
    service: es-deploy
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30001
  - name: "9300"
    port: 9300
    targetPort: 9300
    nodePort: 30002
