apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

bases:
  - volumes/
  
resources:
  - namespace.yaml
  - graylogpw.yaml
  - graylogsecret.yaml
  - graylog-configmap.yaml
  - es-configmap.yaml
  - es-deploy.yaml
  - mongo-deploy.yaml
  - graylog-deploy.yaml
  - fluent-bit-service-account.yaml
  - fluent-bit-role.yaml
  - fluent-bit-role-binding.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemon-set.yaml
namespace: logging
