apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

bases:
  - external-dns/
  - kube-system/
  - logging/
  - github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.0